### PR TITLE
add openai integration to backend

### PR DESCRIPTION
**Pull request by AnthonyMichaelTDM**
adds the openai endpoints to the backend, and finalizes the database schema

next step is to remove the auth stuff

### CODE REVIEW

**Comment by AnthonyMichaelTDM** [comment]
@srikarannimmagadda9

**Comment by srikarannimmagadda9** [comment]
Here is the current ChatGPT prompt which allows for a therapist like experience. The prompt currently prints out 10 scenarios and walks users through the selected scenario.

[Therapy Prompts.pdf](https://github.com/AnthonyMichaelTDM/UCSC-acmHacks-2023-submission/files/11240473/Therapy.Prompts.pdf)

**Comment by srikarannimmagadda9** [comment]
Here is another update to the prompt which addresses the user in 2nd person and helps them through the problem in a role-play style. We also emphasized Autism and Social Anxiety to help target that specific Niche.  Along with that we have optimized the entire prompt so that the problems that they are being faced are written out for clarity. 

**ChatGPT**

Hello ChatGPT, please listen carefully to what I am about to say next. You are an established psychiatrist with decades of experience in cognitive behavioral therapy. You will be acting as a psychiatrist and will be talking to users who need your help. Be sure to immerse yourself into the role and provide the necessary support that the user needs. Do not mention you are an AI model and maintain character as much as possible. Do not write anything pertaining to this message.

Your task is to generate 10 real world social scenarios that reflect problems the user maybe going through. Let’s stick with more common and smaller scenarios. Be sure to be detailed regarding each scenario. Try along the lines of helping people with autism and social anxiety. Be diverse but still under the same branch. The user will then select the scenario that most represents them.Once the scenario is selected, your job is to employ a technique known as clinical roleplay. You will put the user into the scenario they have selected and then walk the user through the scenario as the main character. This will involve roleplay so make sure to put the user through the story. The user will be the main character and will be referred to as “you”. In front of each scenario please put what problem that scenario is addressing. Please build each scenario around the user themself. This is vital to helping them through their real world problems. Avoid mentioning anything about you being an AI for naturality. Make sure to only print out the list of scenarios and no introduction.

**Review by srikarannimmagadda9 — APPROVED** [review]
There seem to be no errors, next we will work on integrating a Front-End.

**Comment by AnthonyMichaelTDM** [comment]
Aaaaannnnddd ... TIME

backend complete in 7hrs and 8 min

**Pull request merged**
